name: Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      - uses: actions/checkout@v3

      - name: Check Ansible Version
        run: ansible --version
        
      - name: Install Python Prerequisites
        run: |
          /opt/pipx/venvs/ansible-core/bin/activate
          /opt/pipx/venvs/ansible-core/bin/python -m pip install boto3 botocore
        
      - name: Check Dynamic Inventory
        run: ansible -i aws_ec2.yml  all  -m ping
      
